"""I/O OBJ + MTL avec coordonnées UV.

Format OBJ minimal (Wavefront) :
    mtllib track.mtl
    v x y z
    vt u v
    f v1/vt1 v2/vt2 v3/vt3

Le `.mtl` référence l'atlas de texture :
    newmtl track_material
    map_Kd atlas.png

Pour les vertex colors, l'extension non-standard est :
    v x y z r g b

On les inclut quand fournies (Blender lit ça via "Color Attribute").
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from numpy.typing import NDArray


def write_obj_with_uvs(
    obj_path: Path,
    *,
    vertices: NDArray[np.float64],
    faces: NDArray[np.int64],
    uvs: NDArray[np.float64],
    mtl_filename: str = "track.mtl",
    material_name: str = "track_material",
    vertex_colors: NDArray[np.float64] | None = None,
) -> int:
    """Écrit un OBJ avec UVs et optionnellement vertex colors.

    Args:
        obj_path : chemin de sortie.
        vertices : (M, 3).
        faces : (F, 3) indices 0-based.
        uvs : (M, 2) ∈ [0, 1]².
        mtl_filename : nom du fichier MTL à référencer (mtllib).
        material_name : nom du material à utiliser (usemtl).
        vertex_colors : (M, 3) optionnel, ∈ [0, 1]³.

    Returns:
        Nombre de bytes écrits.
    """
    if vertices.shape[0] != uvs.shape[0]:
        raise ValueError(
            f"len(vertices) {vertices.shape[0]} != len(uvs) {uvs.shape[0]}"
        )
    obj_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# Generated by road2track ac_export",
        f"mtllib {mtl_filename}",
        f"usemtl {material_name}",
    ]
    if vertex_colors is not None:
        if vertex_colors.shape != vertices.shape:
            raise ValueError(
                f"vertex_colors shape {vertex_colors.shape} != vertices {vertices.shape}"
            )
        for i in range(vertices.shape[0]):
            x, y, z = vertices[i]
            r, g, b = np.clip(vertex_colors[i], 0.0, 1.0)
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f} {r:.4f} {g:.4f} {b:.4f}")
    else:
        for i in range(vertices.shape[0]):
            x, y, z = vertices[i]
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for i in range(uvs.shape[0]):
        u, v = uvs[i]
        lines.append(f"vt {u:.6f} {v:.6f}")
    for f in faces:
        # OBJ index 1-based ; même index pour position et texture.
        a, b_idx, c = int(f[0]) + 1, int(f[1]) + 1, int(f[2]) + 1
        lines.append(f"f {a}/{a} {b_idx}/{b_idx} {c}/{c}")

    text = "\n".join(lines) + "\n"
    obj_path.write_text(text, encoding="utf-8")
    return len(text)


def write_mtl(
    mtl_path: Path,
    *,
    atlas_filename: str,
    material_name: str = "track_material",
) -> int:
    """Écrit un fichier `.mtl` minimal pointant sur l'atlas."""
    mtl_path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        f"# Generated by road2track ac_export\n"
        f"newmtl {material_name}\n"
        f"Ka 1.000 1.000 1.000\n"
        f"Kd 1.000 1.000 1.000\n"
        f"Ks 0.000 0.000 0.000\n"
        f"d 1.0\n"
        f"illum 2\n"
        f"map_Kd {atlas_filename}\n"
    )
    mtl_path.write_text(content, encoding="utf-8")
    return len(content)
